### ISSUE TITLE
Inherit from dbt-postgres

### ISSUE THREAD

**Issue by jtcohen6** [MaterializeInc/dbt-materialize#4]
The `dbt-materialize` plugin depends on `PostgresConnectionManager`, `PostgresCredentials`, `PostgresAdapter`, `PostgresColumn`—which makes a lot of sense, since Materialize is largely compatible with Postgres.

Right now, however, `dbt-materialize` requires only `dbt-core` + `psycopg2`:

https://github.com/MaterializeInc/dbt-materialize/blob/dd58bd0714e33276aa43472e264b377ca53da937/setup.py#L32-L35

If installed from `setup.py`, and I then try to invoke dbt with a `materialize`-type target profile, this results in:
```
$ dbt run
Running with dbt=0.18.1
Error importing adapter: No module named 'dbt.adapters.postgres'
Encountered an error:
No module named 'dbt.adapters.postgres'
```

Instead, I think `dbt-materialize` should explicitly require `dbt-postgres`:
```python
    install_requires=[ 
        'dbt-postgres=={}'.format(package_version)
    ]
```

The plugin would also get "for free" the [special handling for `psycopg2`](https://github.com/fishtown-analytics/dbt/blob/30f473a2b1e261e3f4b712564df854f8a95134f3/plugins/postgres/setup.py#L22-L40) that exists in `dbt-postgres` has today.

**Comment by JLDLaughlin** [comment]
This makes sense! When you see that error installing from `setup.py`, do you mean by running `python setup.py install`? (instead of `pip install ..`?) I'm happy to make this change, but I haven't been able to reproduce the issue locally and want to be sure I'm actually fixing it.

**Comment by benesch** [comment]
Have you tried installing in a virtual env, @JLDLaughlin? That might allow you to repro. Something like this I think:

```
python3 -m venv venv
source venv/bin/activate
pip install dbt-materialize
```

**Comment by JLDLaughlin** [comment]
I have! That doesn't reproduce the issue for me, do you see it trying to install that way @benesch?

**Comment by jtcohen6** [comment]
Updated my description above to be clearer. The error doesn't occur when installing `dbt-materialize` (whether via `pip install .` or `python3 setup.py install`), but rather when I try to invoke dbt from within that virtual environment after installation. The fix is to install `dbt-postgres` into the same virtual environment, since it's an implicit dependency.
